module.exports = [
  '311',
  '96 Bitter Beings',
  'A Perfect Murder',
  'AC/DC',
  'AFI',
  'Ace of Base',
  'Ace of Hearts',
  'Aerosmith',
  'Air',
  'Alanis Morissette',
  'Alice Deejay',
  'Alice in Chains',
  'All Pigs Must Die',
  'Ambulette',
  'American Lesion',
  'Anathema',
  'Andrew W.K.',
  'Angels & Airwaves',
  'Anthrax',
  'ArmsBendBack',
  'Arthur',
  'Atreyu',
  'Austrian Death Machine',
  'Avail',
  'Avenged Sevenfold',
  'Bad Religion',
  'Bars',
  'Bat for Lashes',
  'Baumer',
  'Beanie Sigel',
  'Beastie Boys',
  'Bed of Stars',
  'Bedlight for Blue Eyes',
  'Big Boi',
  'Big Jesus',
  'Black Ribbons',
  'Black Sabbath',
  'Blackened',
  'Blackeye',
  'Bleeding Through',
  'Blink 182',
  'Blink-182',
  'Blondie',
  'Bloodhound Gang',
  'Bob Marley',
  'Brandon Saller',
  'Bullets and Octane',
  'Burn Halo',
  'Bury Your Dead',
  'Bush',
  'CIG',
  'CIV',
  'CKY',
  'Calliope Musicals',
  'Camp Lo',
  'Cancer Bats',
  'Canibus',
  'Carolina Liar',
  'Chris Isaak',
  'Chuck Ragan',
  'Cinema Bizarre',
  'City and Colour',
  'Codeseven',
  'Cokie the Clown',
  'Collective Soul',
  'Convent',
  'Crashdiet',
  'Creed',
  'Crosses',
  'Curl Up and Die',
  'Cypress Hill',
  'Czarface',
  'D12',
  'DJ Clue',
  'DJ Clue?',
  'DJ Shadow',
  'DMX',
  'Damone',
  'Dance Floor Justice',
  'Daniel Davies',
  'Daniel Lioneye',
  'Darkest Hour',
  'David Bowie',
  'Day of Contempt',
  'Death From Above 1979',
  'Deathkiller',
  'Deftones',
  'Denali',
  'Depeche Mode',
  'Deron Miller',
  'Destroy the Machine',
  'Dethklok',
  'Die Trying',
  'Diecast',
  'Dimmu Borgir',
  'Dinosaur Jr',
  'Dinosaur Jr.',
  'Doctor Midnight and the Mercy Cult',
  'Doves',
  'Dr. Dre',
  'Dr. Octagon',
  'EPMD',
  'Earth Crisis',
  'Ed Roland',
  'Ed Roland and the Sweet Tea Project',
  'Eddie Vedder',
  'Eighteen Visions',
  'Eminem',
  'Escondido',
  'Everclear',
  'Evergreen Terrace',
  'Every Time I Die',
  'Far',
  'Fatboy Slim',
  'Fever Ray',
  'Foo Fighters',
  'Foreign Objects',
  'Foxy Shazam',
  'Frou Frou',
  'Fuckface Unstoppable',
  'Funeral for a Friend',
  'Funkmaster Flex',
  'GZA',
  'Garbage',
  'Genesis',
  'Ghostface Killah',
  'Gin Blossoms',
  'Glasvegas',
  'Gnarkill',
  'Gods',
  'Gojira',
  'Goldfinger',
  'Goldfrapp',
  'Gone Without Trace',
  'Green Day',
  'Green Jello',
  'Green Jellö',
  'Greg Graffin',
  'Guns N\' Roses',
  'Gyroscope',
  'HER',
  'HIM',
  'Hank Von Hell',
  'Hardcore Superstar',
  'Head Automatica',
  'Hell or Highwater',
  'Helltrain',
  'Helmet',
  'Hideki',
  'Himsa',
  'Hole',
  'Hootie and the Blowfish',
  'How to Destroy Angels',
  'Humongous',
  'I Am Ghost',
  'I Am War',
  'I Am the Thorn',
  'Ice Cube',
  'Icon and the Black Roses',
  'Ignite',
  'Imogen Heap',
  'In Flames',
  'Incubus',
  'Inspectah Deck',
  'Interpol',
  'Intramural',
  'It Dies Today',
  'J Dilla',
  'Jay Z',
  'Jay-Z',
  'Jem',
  'Jeremy Enigk',
  'Jermaine Dupri',
  'Jerry Cantrell',
  'Jim Adkins',
  'Jimi Hendrix',
  'Jimmy Eat World',
  'Joel Kosche',
  'Josh Haden',
  'Juliana Hatfield',
  'Juliette and the Licks',
  'Jurassic 5',
  'Killer Mike',
  'Kleerup',
  'Korn',
  'Kris Kross',
  'Ké',
  'La Roux',
  'Lacrimas Profundere',
  'Lana Del Rey',
  'Led Zeppelin',
  'Lenny Kravitz',
  'Limp Bizkit',
  'Linkin Park',
  'Local H',
  'Lola Ray',
  'Lorde',
  'Lostprophets',
  'Loud Lucy',
  'Lykke Li',
  'M83',
  'MC Paul Barman',
  'Madonna',
  'Maniac',
  'Maria Andersson',
  'Mariachi El Bronx',
  'Marilyn Manson',
  'Megadeth',
  'Melody Club',
  'Metallica',
  'Method Man',
  'Michael Jackson',
  'Michale Graves',
  'Mike Herrera',
  'Modern Crimes',
  'Morningwood',
  'Most Precious Blood',
  'Muse',
  'MxPx',
  'My Bloody Valentine',
  'My Chemical Romance',
  'N.W.A.',
  'NOFX',
  'Nails',
  'Neverending White Lights',
  'New Order',
  'Newsted',
  'Nine Inch Nails',
  'Nirvana',
  'No Doubt',
  'Noel Gallagher',
  'Noisem',
  'Nonpoint',
  'Nora',
  'Oasis',
  'Ol\' Dirty Bastard',
  'One Day as a Lion',
  'Open Hand',
  'Outkast',
  'Ozzy Osbourne',
  'Pantera',
  'Papa Roach',
  'Patrick Park',
  'Pearl Jam',
  'Pennywise',
  'Pet Shop Boys',
  'Pete Rock',
  'Pharoahe Monch',
  'Phil Collins',
  'Placebo',
  'Poison the Well',
  'Polkadot Cadaver',
  'Priestess',
  'Prince',
  'Probot',
  'Program the Dead',
  'Prophets of Rage',
  'Puff Daddy',
  'Puscifer',
  'Queen',
  'Queens of the Stone Age',
  'R.E.M.',
  'RZA',
  'Radiohead',
  'Raekwon',
  'Rage Against the Machine',
  'Ramones',
  'Rancid',
  'Ratking',
  'Recon',
  'Red Hot Chili Peppers',
  'Redman',
  'Reel Big Fish',
  'Refused',
  'Reprazent',
  'Richard Ashcroft',
  'Roadrunner United',
  'Rob Zombie',
  'Robert Miles',
  'Robyn',
  'Roni Size',
  'Royksopp',
  'Rudy + Blitz',
  'Run the Jewels',
  'Röyksopp',
  'Royksopp',
  'S.O.S.',
  'Sahara Hotnights',
  'Scarlet',
  'Scars on Broadway',
  'Scissor Sisters',
  'Scott Lucas and the Married Men',
  'Self',
  'Sheryl Crow',
  'Sigur Ros',
  'Sigur Rós',
  'Silverchair',
  'Smashing Pumpkins',
  'Snoop Dogg',
  'Soul Asylum',
  'Soundgarden',
  'Spain',
  'Steel Panther',
  'Sticky Fingaz',
  'Stone Temple Pilots',
  'Sublime',
  'Suffer Well',
  'Sugar Ray',
  'Sunz of Man',
  'Surferosa',
  'Sway & King Tech',
  'System of a Down',
  'Tash',
  'Taylor Hawkins',
  'Taylor Hawkins and the Coattail Riders',
  'Terror',
  'Tha Alkaholiks',
  'Tha Liks',
  'The 69 Eyes',
  'The Album Leaf',
  'The Bled',
  'The Bloodhound Gang',
  'The Break',
  'The Bronx',
  'The Classic Crime',
  'The Cootees',
  'The Cure',
  'The Damned Things',
  'The Darkness',
  'The Devin Townsend Project',
  'The Dillinger Escape Plan',
  'The Distance',
  'The Distillers',
  'The Drips',
  'The Evesdroppers',
  'The Federal Empire',
  'The Hellacopters',
  'The Hope Conspiracy',
  'The Iron Son',
  'The Killers',
  'The Kinison',
  'The Matches',
  'The Misfits',
  'The Mistake',
  'The Moody Blues',
  'The Notorious B.I.G.',
  'The Offspring',
  'The Postal Service',
  'The Preatures',
  'The Presidents of the United States of America',
  'The Prodigy',
  'The Rasmus',
  'The Sounds',
  'The Streets',
  'The Submarines',
  'The Sweet Tea Project',
  'The Ting Tings',
  'The Vandals',
  'The Velvet Teen',
  'The Veronicas',
  'The Vows',
  'Thomas Giles',
  'Throwdown',
  'Tim Barry',
  'To Die For',
  'Toadies',
  'Tom DeLonge',
  'Tom Petty',
  'Tool',
  'Tumbledown',
  'Turbonegro',
  'Turnstile',
  'Unearth',
  'Unkle',
  'Unkle Matt and the Shitbirdz',
  'VV',
  'Vaux',
  'Ville Valo & Agents',
  'Vocal Few',
  'Volbeat',
  'Walls of Jericho',
  'Weeping Willows',
  'Weezer',
  'White Sea',
  'White Zombie',
  'Will Turpin',
  'Within Temptation',
  'World Under Blood',
  'Wu-Tang Clan',
  'Xzibit',
  'You+Me',
  'Zimmers Hole',
];
